name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci
      - name: Build preview
        if: github.event.action != 'closed'
        run: npm run build -- --base="/ttp-play-dates/pr-preview/pr-${{ github.event.number }}/"
      - name: Ensure dist directory exists for teardown
        if: github.event.action == 'closed'
        run: mkdir -p dist
      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1.6.2
        with:
          source-dir: dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
